# Generated by Django 3.2.4 on 2021-07-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_char', models.CharField(max_length=30)),
                ('test_email', models.EmailField(max_length=254)),
                ('test_integer', models.IntegerField()),
                ('test_float', models.IntegerField()),
            ],
        ),
    ]
